### ISSUE TITLE
Problems with example

### ISSUE THREAD

**Issue by PascalG14** [sovrin-foundation/old-sovrin#16]
Hello, 
I experimented with Sovrin and followed the instructions of "Getting Started with Sovrin". I tried to achieve the same results as in the example and had several problems. 
First Sovrin was not able to connect to FCUC and it was not possible to accept the invitation of Faber College. I tried it a few times and sometimes it worked and sometimes it did not.
When it was possible to accept the invitation there was an other problem. I did not receive the "Transcript", so I was not able to go on. Like the first problem it was not regularly.
The last problem I had was that Sovrin broke down after I had sent the "Job-Application" to Acme Corp.
Do you have any ideas why it worked different every time I tried it?

**Comment by dhh1128** [comment]
We were pushing code during the day today, so you may have had different behaviors during the push. This is not normal; we had to reset some nodes. This tweaking will likely occur one or two more times until about noon tomorrow, Pacific time. Please try again after that, and tell us if you have further difficulties.

**Comment by PascalG14** [comment]
"Thank you for the fast answer. I was able to test it again and almost everything worked well. The only problem I still have is that Sovrin breaks down when I send the "Job-Application":

ALICE@test> send claim Job-Application to Acme Corp
Error while running coroutine shell: ValueError('too many values to unpack (expected 2)',)
Traceback (most recent call last):
File "/usr/local/bin/sovrin", line 76, in
run_cli()
File "/usr/local/bin/sovrin", line 54, in run_cli
looper.run(cli.shell(commands))
File "/home/blockchain/.local/lib/python3.5/site-packages/plenum/common/looper.py", line 240, in run
return self.loop.run_until_complete(what)
File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
return future.result()
File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
raise self.exception
File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in step
result = coro.send(None)
File "/home/blockchain/.local/lib/python3.5/site-packages/plenum/common/looper.py", line 231, in wrapper
raise ex
File "/home/blockchain/.local/lib/python3.5/site-packages/plenum/common/looper.py", line 219, in wrapper
results.append(await coro)
File "/home/blockchain/.local/lib/python3.5/site-packages/plenum/cli/cli.py", line 977, in shell
self.parse(c)
File "/home/blockchain/.local/lib/python3.5/site-packages/plenum/cli/cli.py", line 1291, in parse
r = action(matchedVars)
File "/usr/local/lib/python3.5/dist-packages/sovrin/cli/cli.py", line 1318, in _sendClaim
self._sendReqToTargetEndpoint(op, link)
File "/usr/local/lib/python3.5/dist-packages/sovrin/cli/cli.py", line 976, in _sendReqToTargetEndpoint
self.sendToAgent(op, link)
File "/usr/local/lib/python3.5/dist-packages/sovrin/cli/cli.py", line 304, in sendToAgent
self.agent.connectTo(link.name)
File "/usr/local/lib/python3.5/dist-packages/sovrin/agent/walleted.py", line 707, in connectTo
self.connectToHa(ha)
File "/usr/local/lib/python3.5/dist-packages/sovrin/agent/agent.py", line 117, in connectToHa
self.endpoint.connectTo(ha)
File "/usr/local/lib/python3.5/dist-packages/sovrin/agent/endpoint.py", line 65, in connectTo
remote = RemoteEstate(stack=self, ha=ha)
File "/home/blockchain/.local/lib/python3.5/site-packages/raet/road/estating.py", line 245, in __init
super(RemoteEstate, self).init(stack, uid=uid, *kwa)
File "/home/blockchain/.local/lib/python3.5/site-packages/raet/road/estating.py", line 60, in init
host, port = ha
ValueError: too many values to unpack (expected 2)
blockchain@ESNBBLOCKCHAIN:~$

Do you know why this still happens ?"

**Comment by lovesh** [comment]
@PascalG14 Looks like you are using an older version of `sovrin`. I can say this from looking at the stacktrace. According to the stacktrace, `sendToAgent` has line `self.agent.connectTo(link.name)` but in the current codebase, `sendToAgent` has no such line. Can you upgrade sovrin by `pip install -U --no-cache-dir sovrin`?

**Comment by PascalG14** [comment]
Thank you. Now it works.

**Comment by lovesh** [comment]
@PascalG14 Your welcome
